### PR TITLE
Fix update-version.sh for ucxx.

### PR DESCRIPTION
**Pull request by bdice**
This PR fixes an issue in `update-version.sh` that deleted a trailing `}`, making the `manifest.yaml` invalid.

### CODE REVIEW

**Review by trxcllnt — APPROVED** [review]

**Comment by trxcllnt** [comment]
Is there a way to make [this commit](https://github.com/rapidsai/devcontainers/commit/51d3b93729f339967c547e00fc3b67ce3ae7f694) not include `[skip ci]`?

**Comment by trxcllnt** [comment]
Also, looking at that commit in more depth -- lines [like this](https://github.com/rapidsai/devcontainers/commit/51d3b93729f339967c547e00fc3b67ce3ae7f694#diff-58a825c70bccfbe691d7ddbddb133275f4f657de6aeb4a502fa9fce279f8bf8dR26) are wrong. Specifically the image tags should be:

```diff
- ghcr.io/rapidsai/devcontainers/features/cmake:24.06
+ ghcr.io/rapidsai/devcontainers/features/cmake:24.6
```

Is this something we do in `update_versions.sh`?

**Comment by trxcllnt** [comment]
CI is failing because [dask-cuda and ucx-py aren't published yet](https://github.com/rapidsai/devcontainers/actions/runs/8303408179/job/22727482699?pr=247#step:7:1408). Maybe we should build those from source too?

**Comment by bdice** [comment]
> Is there a way to make [this commit](https://github.com/rapidsai/devcontainers/commit/51d3b93729f339967c547e00fc3b67ce3ae7f694) not include `[skip ci]`?

I've discussed this with @raydouglass before, I'll let him explain. In my understanding, there's no good way to do this for new branches according to the present branching process.

**Comment by bdice** [comment]
> Also, looking at that commit in more depth -- lines [like this](https://github.com/rapidsai/devcontainers/commit/51d3b93729f339967c547e00fc3b67ce3ae7f694#diff-58a825c70bccfbe691d7ddbddb133275f4f657de6aeb4a502fa9fce279f8bf8dR26) are wrong. The feature tags should be:
> 
> ```diff
> - ghcr.io/rapidsai/devcontainers/features/cmake:24.06
> + ghcr.io/rapidsai/devcontainers/features/cmake:24.6
> ```
> 
> Is this something we do in `update_versions.sh`?

Yes. Fixed in 0ac487f. Let me know if anything else seems off.

**Comment by bdice** [comment]
> CI is failing because [dask-cuda and ucx-py aren't published yet](https://github.com/rapidsai/devcontainers/actions/runs/8303408179/job/22727482699?pr=247#step:7:1408). Maybe we should build those from source too?

No packages are available yet -- we'll have to wait until tonight's nightly trigger to run the build pipeline for all of RAPIDS. This can wait until Monday, or we can request an admin-merge but that's probably not meaningful so close to the weekend.

**Comment by trxcllnt** [comment]
> I've discussed this with @raydouglass before, I'll let him explain. In my understanding, there's no good way to do this for new branches according to the present branching process.

Here's how I [was doing it](https://github.com/rapidsai/devcontainers/pull/156) before:
1. Create `branch-24.06` from `branch-24.04` and push it
2. Create `update-to-24.06` branch from `branch-24.06`
3. Run update script in `update-to-24.06` branch
4. Open PR from `update-to-24.06` to `branch-24.06` and merge once tests pass

Any reason we can't do this again?

**Comment by bdice** [comment]
> CI is failing because [dask-cuda and ucx-py aren't published yet](https://github.com/rapidsai/devcontainers/actions/runs/8303408179/job/22727482699?pr=247#step:7:1408). Maybe we should build those from source too?

To answer your question directly: we could build these in devcontainers. I don't see anything that would block us, but I don't feel strongly about it. It would make devcontainers more self-contained / hermetic. I'm fine with waiting for nightlies to make packages, but if you'd like to add them, I can review.

**Comment by bdice** [comment]
> 1. Create `branch-24.06` from `branch-24.04` and push it

This is the problematic part. For most of RAPIDS, pushing `branch-24.06` will trigger packages to build, but they'll have 24.04 version numbers until `update-version.sh` is run. Having 24.06 packages with version numbers from 24.04 is problematic. Thus, you have to run `update-version.sh` before pushing `branch-24.06`.

**Comment by trxcllnt** [comment]
That's fine, like I said we can make a staging branch and rename it once the update is merged.

**Pull request merged**
