### PR TITLE
Upgrade CCCL clang-format to version 18

### PR DESCRIPTION
**Pull request by bernhardmgruber**
Fixes: #341

### CODE REVIEW

**Comment by trxcllnt** [comment]
@bernhardmgruber This looks good to me. Once we merge this and publish new containers, clang-format-18 could potentially produce different formatting than 17 for users. Does merging this need to be sync'd with a PR that updates/re-formats CCCL sources?

**Comment by bernhardmgruber** [comment]
@trxcllnt yes, it needs to be synced with this PR in CCCL: https://github.com/NVIDIA/cccl/pull/1928. I can take care of this once you merge.

**Comment by trxcllnt** [comment]
Ok, I'll merge this now and new images should be published shortly after.

**Pull request merged**
